//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbcNewPeripheral
    {
        public int UniqNo { get; set; }
        public string PeripheralName { get; set; }
        public string PeripheralSerailNo { get; set; }
        public string PeripheralStatus { get; set; }
        public string PPSAssignedToEmpID { get; set; }
        public string PPSAssignedToEmpName { get; set; }
        public string PPSAssignedToEmailAddress { get; set; }
        public string PPSWarrentyStatus { get; set; }
        public Nullable<System.DateTime> PPSWarrentyStartDate { get; set; }
        public Nullable<System.DateTime> PPSWarrentyEndDate { get; set; }
    }
}
