//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMBCITRptUpload
    {
        public string EmployeeName { get; set; }
        public string EmpAssetID { get; set; }
        public string ReportMonth { get; set; }
        public string ReportType { get; set; }
        public string UploadReportPathDetail { get; set; }
        public string UploadRemarks { get; set; }
        public string UploadedByID { get; set; }
        public string UploadedByName { get; set; }
        public string UploadedByEmail { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string EmpClient { get; set; }
    }
}
