//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMBC_Active_Emp_view
    {
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Contact_Number { get; set; }
        public string Designation { get; set; }
        public string Client_Report_Manager { get; set; }
        public string AMBC_Project_Manager { get; set; }
        public string AMBC_PM_Mail_Address { get; set; }
        public string Client { get; set; }
        public string Shift { get; set; }
        public string Project_Name { get; set; }
        public string Project_Status { get; set; }
        public bool Employee_Status { get; set; }
        public string Location { get; set; }
        public string AMBC_Mail_Address { get; set; }
        public Nullable<System.DateTime> Employee_Joining_Day { get; set; }
        public string Employee_Image_Path { get; set; }
        public int Project_Code { get; set; }
        public string Access_Role { get; set; }
        public string Client_Project_Name { get; set; }
        public string Roles_Responsibilities { get; set; }
    }
}
