//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMBC_Active_Emp
    {
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_mobile { get; set; }
        public string proj_client { get; set; }
        public string project_shift { get; set; }
        public bool emp_status { get; set; }
        public string region { get; set; }
    }
}
