//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbcNewITAssetMgmt
    {
        public int UniqNo { get; set; }
        public string AssetSerialNo { get; set; }
        public string AssetType { get; set; }
        public string AssetManufacturer { get; set; }
        public string AssetModel { get; set; }
        public string AssetHostName { get; set; }
        public string AssetMacNo { get; set; }
        public string ChargerSerialNo { get; set; }
        public string ChargerCapicity { get; set; }
        public string DisplaySize { get; set; }
        public string RAM_Size { get; set; }
        public string ROM_Size { get; set; }
        public string USBPortStatus { get; set; }
        public string WarrentyStatus { get; set; }
        public Nullable<System.DateTime> WarrentyStartDate { get; set; }
        public Nullable<System.DateTime> WarrentyEndDate { get; set; }
        public string OperatingSystemDetail { get; set; }
        public Nullable<System.DateTime> Lastupdated { get; set; }
        public string ServiceTag { get; set; }
        public string SoldOutStatus { get; set; }
        public Nullable<System.DateTime> SoldOutDate { get; set; }
        public string SoldOutVendor { get; set; }
        public Nullable<int> SoldoutPrice { get; set; }
        public string AssetPurchaseLocation { get; set; }
        public string AssetPurchaseVendor { get; set; }
        public string AssetDescription { get; set; }
        public string HeadsetDetail { get; set; }
        public string AssetRemarks { get; set; }
        public string MouseDetail { get; set; }
        public string AccessControl { get; set; }
        public string AssetUploadedByEmpid { get; set; }
        public string AssetUploadedByEmpName { get; set; }
        public string AssetUploadedByEmpEmailAddress { get; set; }
        public string AssetAllocationStatus { get; set; }
        public Nullable<System.DateTime> AssetEntryCreatedDate { get; set; }
        public Nullable<System.DateTime> AssetEntryModifiedDate { get; set; }
    }
}
