//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmbcClient
    {
        public int Clientid { get; set; }
        public string ClientName { get; set; }
        public string ClientAddress { get; set; }
        public string ClientDescription { get; set; }
        public string ServicesProvidedByClient { get; set; }
        public string ServicesProvidedByAMBC { get; set; }
        public string CleintSF { get; set; }
    }
}
