//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetAllocationMgmt
    {
        public int UniqNo { get; set; }
        public string AssetSerialNo { get; set; }
        public string AssetType { get; set; }
        public string AssetHostName { get; set; }
        public string AssetMacNo { get; set; }
        public string AssetTxn { get; set; }
        public string AssetAllocatedToEmpID { get; set; }
        public string AssetAllocatedToEmpName { get; set; }
        public string AssetAllocatedToEmailAddress { get; set; }
        public string AssetAllocatedToMobileNo { get; set; }
        public string AssetAllocatedByEmpID { get; set; }
        public string AssetAllocatedByEmpName { get; set; }
        public string AssetAllocatedByEmail { get; set; }
        public string AssetAllocatedByMobile { get; set; }
        public string AssetAllocationRemarks { get; set; }
        public Nullable<System.DateTime> AssetAllocationCreatedDate { get; set; }
        public Nullable<System.DateTime> AssetAllocationModifiedDate { get; set; }
    }
}
