//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class con_leaveupdate20220510
    {
        public int leaveno { get; set; }
        public Nullable<System.DateTime> leavedate { get; set; }
        public string employee_id { get; set; }
        public string leave_reason { get; set; }
        public string submittedby { get; set; }
        public string leavesource { get; set; }
        public string leaveuniqkey { get; set; }
    }
}
