//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultantavailiability2
    {
        public string Employee_Code { get; set; }
        public string Month_year { get; set; }
        public string Leave_Type { get; set; }
        public Nullable<decimal> LeaveTypeValue { get; set; }
        public Nullable<int> TXNCount { get; set; }
    }
}
