//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultantavailiability_Final
    {
        public string Employee_Code { get; set; }
        public string Month_Year { get; set; }
        public Nullable<decimal> Consultant_WorkedDays { get; set; }
        public Nullable<int> Monthly_WorkingDays { get; set; }
        public string ConslAvl { get; set; }
    }
}
