//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class desk_att_taskcapture
    {
        public int timesheetno { get; set; }
        public Nullable<int> weekno { get; set; }
        public Nullable<System.DateTime> weekstartdate { get; set; }
        public Nullable<System.DateTime> weekenddate { get; set; }
        public string employeeid { get; set; }
        public string employeename { get; set; }
        public string employeedesignation { get; set; }
        public string employeemailid { get; set; }
        public string employeereportingmgr { get; set; }
        public string employeecontactno { get; set; }
        public string employeeassignclientname { get; set; }
        public string employeeprojectname { get; set; }
        public string project_status { get; set; }
        public Nullable<int> day1 { get; set; }
        public Nullable<int> day2 { get; set; }
        public Nullable<int> day3 { get; set; }
        public Nullable<int> day4 { get; set; }
        public Nullable<int> day5 { get; set; }
        public Nullable<int> day6 { get; set; }
        public Nullable<int> day7 { get; set; }
        public Nullable<int> totalhrsworked { get; set; }
        public string worksts1 { get; set; }
        public string taskcategory1 { get; set; }
        public string tasksdone1 { get; set; }
        public string worksts2 { get; set; }
        public string taskcategory2 { get; set; }
        public string tasksdone2 { get; set; }
        public string worksts3 { get; set; }
        public string taskcategory3 { get; set; }
        public string tasksdone3 { get; set; }
        public string worksts4 { get; set; }
        public string taskcategory4 { get; set; }
        public string tasksdone4 { get; set; }
        public string worksts5 { get; set; }
        public string taskcategory5 { get; set; }
        public string tasksdone5 { get; set; }
        public string worksts6 { get; set; }
        public string taskcategory6 { get; set; }
        public string tasksdone6 { get; set; }
        public string worksts7 { get; set; }
        public string taskcategory7 { get; set; }
        public string tasksdone7 { get; set; }
        public string submittedsysname { get; set; }
        public Nullable<int> currentyear { get; set; }
        public string shiftdetail { get; set; }
        public string remarks1 { get; set; }
        public string remarks2 { get; set; }
        public string weeknoempid { get; set; }
    }
}
