//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_info
    {
        public string employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_desg { get; set; }
        public string employee_mailid { get; set; }
        public string employee_mobile { get; set; }
        public string employee_report_manager { get; set; }
        public string employee_sys_hostname { get; set; }
        public string employee_sys_macno { get; set; }
        public string employee_sys_usrname { get; set; }
        public Nullable<int> CategoryTypeID { get; set; }
        public string ambc_manager { get; set; }
        public string ambc_manager_mailid { get; set; }
        public Nullable<System.DateTime> emp_joindate { get; set; }
    }
}
