//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_project_log
    {
        public int uniqprojno { get; set; }
        public string proj_name { get; set; }
        public string proj_client { get; set; }
        public string assign_emp_id { get; set; }
        public string assign_emp_name { get; set; }
        public string project_staus { get; set; }
        public string project_shift { get; set; }
    }
}
