//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplogin
    {
        public string att_username { get; set; }
        public string att_password { get; set; }
        public string att_email { get; set; }
        public string att_role { get; set; }
        public string employee_name { get; set; }
        public string employee_id { get; set; }
        public string employee_hostname { get; set; }
        public string employee_mobile { get; set; }
        public string usrnmconcat { get; set; }
        public string region { get; set; }
        public bool emp_status { get; set; }
    }
}
