//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeSheetEntities : DbContext
    {
        public TimeSheetEntities()
            : base("name=TimeSheetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ambctaskcapture> ambctaskcaptures { get; set; }
        public virtual DbSet<con_leaveupdate> con_leaveupdate { get; set; }
        public virtual DbSet<desk_att_taskcapture> desk_att_taskcapture { get; set; }
        public virtual DbSet<emp_info> emp_info { get; set; }
        public virtual DbSet<emp_info_log> emp_info_log { get; set; }
        public virtual DbSet<emp_project> emp_project { get; set; }
        public virtual DbSet<emp_project_log> emp_project_log { get; set; }
        public virtual DbSet<emplogin> emplogins { get; set; }
        public virtual DbSet<emplogin_log> emplogin_log { get; set; }
        public virtual DbSet<Error_Log> Error_Log { get; set; }
        public virtual DbSet<tbl_ambclogininformation> tbl_ambclogininformation { get; set; }
        public virtual DbSet<tbl_LoginInformation> tbl_LoginInformation { get; set; }
        public virtual DbSet<tblambcholiday> tblambcholidays { get; set; }
        public virtual DbSet<tblambcholidaylog> tblambcholidaylogs { get; set; }
        public virtual DbSet<timesheet_submission_log> timesheet_submission_log { get; set; }
        public virtual DbSet<TimeSheet> TimeSheets { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryList> CategoryLists { get; set; }
        public virtual DbSet<CategoryType> CategoryTypes { get; set; }
        public virtual DbSet<con_leaveupdate_12072021> con_leaveupdate_12072021 { get; set; }
        public virtual DbSet<con_leaveupdate_20220517> con_leaveupdate_20220517 { get; set; }
        public virtual DbSet<con_leaveupdate20220510> con_leaveupdate20220510 { get; set; }
        public virtual DbSet<tbl_LoginInformation_bkp> tbl_LoginInformation_bkp { get; set; }
        public virtual DbSet<tblambcholiday_06May2022> tblambcholiday_06May2022 { get; set; }
        public virtual DbSet<ticket_category> ticket_category { get; set; }
        public virtual DbSet<ticket_priority> ticket_priority { get; set; }
        public virtual DbSet<AMBC_Active_Emp> AMBC_Active_Emp { get; set; }
        public virtual DbSet<AMBC_Active_Emp_view> AMBC_Active_Emp_view { get; set; }
        public virtual DbSet<today_att> today_att { get; set; }
    }
}
