//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Log
    {
        public int ErrorId { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> ErrorTime { get; set; }
        public string ErrorMsg { get; set; }
    }
}
