//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class halfday_leave_view
    {
        public string Employee_Code { get; set; }
        public System.DateTime Sign_In_Date { get; set; }
        public Nullable<System.DateTime> Leave_Date { get; set; }
        public string Leave_Type { get; set; }
    }
}
