//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthlyreports_Template2
    {
        public string Project_Name { get; set; }
        public string Project_Summary { get; set; }
        public System.DateTime Project_Created_Date { get; set; }
        public Nullable<System.DateTime> Project_Closing_Date_Target { get; set; }
        public string Project_Category { get; set; }
        public string Project_Raisedby { get; set; }
        public string Project_Priority { get; set; }
        public string Project_Status { get; set; }
        public Nullable<System.DateTime> Project_Closed_Date_Actual { get; set; }
        public string Organisation { get; set; }
        public string Comments { get; set; }
        public string ConsultantName { get; set; }
        public string Uploaded_Month { get; set; }
        public string uniquekey { get; set; }
        public string Uploadedby { get; set; }
        public string FileNamee { get; set; }
        public string Client_Name { get; set; }
        public string EmplyeeID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<decimal> CompletedPercentage { get; set; }
        public Nullable<decimal> RemainingPercentage { get; set; }
    }
}
