//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthlyreports_Template3
    {
        public string Test_ID { get; set; }
        public string Control_Group_Name { get; set; }
        public string Test_Completed { get; set; }
        public Nullable<System.DateTime> Test_Due_Date { get; set; }
        public Nullable<System.DateTime> Test_Completion_Date { get; set; }
        public string Test_Conclusion { get; set; }
        public string Control_Owner { get; set; }
        public string Control_Performer { get; set; }
        public string Test_application { get; set; }
        public string Organisation { get; set; }
        public string Layer { get; set; }
        public string Frequency { get; set; }
        public string Current_step { get; set; }
        public string Comments { get; set; }
        public string Consultantname { get; set; }
        public string Uploadedmonth { get; set; }
        public string Uniquekey { get; set; }
    }
}
