//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class monthlyreports_Template1
    {
        public string Ticket_Number { get; set; }
        public string Ticket_Summary { get; set; }
        public System.DateTime Ticket_Created_Date { get; set; }
        public string Ticket_Category { get; set; }
        public string Ticket_Raisedby { get; set; }
        public string Ticket_Priority { get; set; }
        public string Ticket_Status { get; set; }
        public Nullable<System.DateTime> Ticket_Closed_Date { get; set; }
        public string Organisation { get; set; }
        public string Comments { get; set; }
        public string Consultant_Name { get; set; }
        public string Uploaded_Month { get; set; }
        public string Uniquekey { get; set; }
        public string Uploadedby { get; set; }
        public string FileNamee { get; set; }
        public Nullable<bool> Is_Newly_created { get; set; }
        public Nullable<bool> Is_Open { get; set; }
        public Nullable<bool> Is_Closed { get; set; }
        public Nullable<int> Ticket_Age { get; set; }
        public string ReportPriority { get; set; }
        public string Client_Name { get; set; }
    }
}
