//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Vendor_Detail
    {
        public int UniqNo { get; set; }
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
        public string VendorCity { get; set; }
        public string VendorEmailAddress { get; set; }
        public string VendorStatus { get; set; }
        public string VendorTxn { get; set; }
        public string VendorRemarks { get; set; }
        public Nullable<System.DateTime> VendorCreatedDate { get; set; }
        public Nullable<System.DateTime> VendorModifiedDate { get; set; }
        public string VendorContactNumber { get; set; }
    }
}
