//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblambcholiday_06May2022
    {
        public int holidayno { get; set; }
        public Nullable<System.DateTime> holiday_date { get; set; }
        public string holiday_name { get; set; }
        public string region { get; set; }
    }
}
