//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblambcholidaylog
    {
        public int ambcholidaylog { get; set; }
        public Nullable<System.DateTime> holiday_date { get; set; }
        public string employee_name { get; set; }
        public string employee_id { get; set; }
        public string employee_hostname { get; set; }
        public string emp_avl_sts { get; set; }
        public string backup_resource { get; set; }
        public string empcontact_no { get; set; }
        public string empidhldydt { get; set; }
    }
}
