//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public int tslogno { get; set; }
        public string employeeid { get; set; }
        public string employeename { get; set; }
        public string empdesignation { get; set; }
        public string empmanager { get; set; }
        public string empcontactnumber { get; set; }
        public string clientname { get; set; }
        public string projectname { get; set; }
        public string projstatus { get; set; }
        public string taskdate { get; set; }
        public string category { get; set; }
        public string incidentnumber { get; set; }
        public string taskdetails { get; set; }
        public string requester { get; set; }
        public string callpriority { get; set; }
        public string callstatus { get; set; }
        public string closeddate { get; set; }
        public string timespent { get; set; }
        public string comments { get; set; }
    }
}
