//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet_submission_log
    {
        public int submissionid { get; set; }
        public Nullable<int> weekno { get; set; }
        public Nullable<int> curryear { get; set; }
        public string employee_name { get; set; }
        public string employee_id { get; set; }
        public string submitted_client { get; set; }
        public string submitted_project { get; set; }
        public Nullable<System.DateTime> submitted_time { get; set; }
        public string submitted_ipaddress { get; set; }
        public string submitted_hostname { get; set; }
    }
}
