//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenderQtnMgmt
    {
        public int UniqNo { get; set; }
        public string QuotationNumber { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public Nullable<int> QuotationAmount { get; set; }
        public string QuotationParticulers { get; set; }
        public string VendorName { get; set; }
        public string VendorAddress { get; set; }
        public string Level1ApprovarName { get; set; }
        public string Level1ApprovalStatus { get; set; }
        public string Level1ApprovalComments { get; set; }
        public string Level2ApprovarName { get; set; }
        public string Level2ApprovalStatus { get; set; }
        public string Level2ApprovalComments { get; set; }
        public string QuotationFinalStatus { get; set; }
        public string QuotationFinalRemarks { get; set; }
    }
}
